export interface defaultThemeInterface {
    yellowLight: string,
    yellow: string,
    yellowDark: string,
    purpleLight: string,
    purple: string,
    purpleDark: string,
    baseTitle: string,
    baseSubtTitle: string,
    baseText: string,
    baseLabel:string,
    baseHover: string,
    baseButton: string,
    baseInput: string,
    baseCard: string,
    background: string,
    white: string, 
    powerpink: string,
    darkpink: string,
    lightpink: string,
    poweryellow: string,
    acqua: string,
}
export const defaultTheme: defaultThemeInterface = {
    yellowLight: '#FF9',
    yellow: '#66F',
    yellowDark: '#0BB',
    purpleLight: '#EBE5F9',
    purple: '#D38',
    purpleDark: '#825',
    baseTitle: '#D06',
    baseSubtTitle: '#C06',
    baseText: '#D06',
    baseLabel:'#B36',
    baseHover: '#FBB',
    baseButton: '#FDD',
    baseInput: '#EDEDED',
    baseCard: '#FFD',
    background: '#FEE',
    white: '#FFD', 
    powerpink: '#F38',
    darkpink: '#805',
    lightpink: '#F6A',
    poweryellow: '#FF3',
    acqua: '#7FF',
};